In [1]:
test = "Hello, World"
print(test)

Hello, World


# NUMPY and MATRICES

In [2]:
import numpy as np

### BASICS


In [9]:
one_dim_arr = np.array([12,20])
print(one_dim_arr)

# creating array from 3 ints starting from 0
arr = np.arange(3)
print(arr)

#starts with one, ends at 20, incremented by 3
arr = np.arange(1,20,3)
print(arr)

#Arrays with evenly spaced values from a given range of numbers: linspace (linear space)
arr = np.linspace(0,100,5, dtype=int) # start, end, number of elements. specified dtype as  float64 is default
print(arr)
print(type(arr[0]))

[12 20]
[0 1 2]
[ 1  4  7 10 13 16 19]
[  0  25  50  75 100]
<class 'numpy.int64'>


### Multi-dimensional Arrays

In [14]:
one_dim_arr = [6,5,4,3,2,1]
two_dim_arr = np.array([[1,2,3],[4,5,6]])
print(two_dim_arr)

#reshaping 1d array to multi dim array
arr = np.reshape(
    one_dim_arr,
    (2,3)
)
print(arr)

[[1 2 3]
 [4 5 6]]
[[6 5 4]
 [3 2 1]]


In [ ]:
print(arr.shape) # m x n
print(arr.size)  # number of elements
print(arr.ndim)  # dimensions

(2, 3)
6
2


### Array Math Operations

In [18]:
arr_1 = np.array([2, 4, 6])
arr_2 = np.array([1, 3, 5])


In [21]:
#adding subtracting 2 1d arrays
sum = arr_1+arr_2
diff = arr_1 - arr_2
print(sum)
print(diff)

# multiplication
prod = arr_1*arr_2
print(prod)

[ 3  7 11]
[1 1 1]
[ 2 12 30]


In [22]:
# Scalar vector multiplicaton (Broadcasting)
print(arr_1 * 3)

[ 6 12 18]


### Indexing and Slicing

In [27]:
a = np.array([1,2,3,4,5])
print(a[2])

two_dim = np.array(([1, 2, 3],
          [4, 5, 6], 
          [7, 8, 9]))

print(arr[0][2])

3
4


In [34]:
sliced_arr = a[2:4]
print(sliced_arr)

sliced_arr = a[:3]
print(sliced_arr)

sliced_arr = a[3:]
print(sliced_arr)

sliced_arr = a[::2] #step count 2
print(sliced_arr)

sliced_arr_2 = two_dim[1:3]
print(sliced_arr_2)

[3 4]
[1 2 3]
[4 5]
[1 3 5]
[[4 5 6]
 [7 8 9]]


### Stacking

In [35]:
a1 = np.array([[1,1], 
               [2,2]])
a2 = np.array([[3,3],
              [4,4]])
print(f'a1:\n{a1}')
print(f'a2:\n{a2}')

a1:
[[1 1]
 [2 2]]
a2:
[[3 3]
 [4 4]]


In [36]:
vert_stack = np.vstack((a1,a2))
print(vert_stack)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [38]:
hor_stack = np.hstack((a1,a2))
print(hor_stack)

[[1 1 3 3]
 [2 2 4 4]]
