## Solving Systems of Linear Equations

In [3]:
import numpy as np
import matplotlib.pyplot as plt

In [4]:
# creating the matrix:
A = np.array([[-1,3],[3,2]],dtype=np.dtype(float))
b = np.array([7,1],dtype=np.dtype(float))
print("Matrix A:")
print(A)
print("Matrix B")
print(b)

Matrix A:
[[-1.  3.]
 [ 3.  2.]]
Matrix B
[7. 1.]


In [5]:
# confirming dimensions of a and b
print(np.shape(A))
print(np.shape(b))

(2, 2)
(2,)


In [6]:
# simplified approach to solving a linear equation using numpy's linear algebra package
x = np.linalg.solve(A,b)
print(f"Solution : {x}")

Solution : [-1.  2.]


In [9]:
# similarly it also provides determinant evaluation
det = np.linalg.det(A)
print(f"{det:.2f}")

-11.00


In [11]:
A_system = np.hstack((A,b.reshape(2,1)))
print(A_system)

[[-1.  3.  7.]
 [ 3.  2.  1.]]


In [12]:
# linear eq with no sol
A_2 = np.array([
        [-1, 3],
        [3, -9]
    ], dtype=np.dtype(float))

b_2 = np.array([7, 1], dtype=np.dtype(float))

d_2 = np.linalg.det(A_2)

print(f"Determinant of matrix A_2: {d_2:.2f}")

Determinant of matrix A_2: 0.00


In [13]:
try:
    x_2 = np.linalg.solve(A_2, b_2)
except np.linalg.LinAlgError as err:
    print(err)

Singular matrix
