In [2]:
import numpy as np

In [3]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [4]:
print(a.shape)
a.ndim

(3, 5)


2

In [5]:
a.dtype.name

'int32'

In [6]:
a.itemsize #prints the of each element in bytes

4

In [7]:
a.size #prints the total number of elements in the array

15

In [8]:
type(a)

numpy.ndarray

In [9]:
l = [1,2,3,4,5]
lnp = np.array(l) #converting a python list to numpy array
print(lnp.dtype)
print(type(lnp))

int32
<class 'numpy.ndarray'>


# Array Creation

In [10]:
a2 = np.array([1.2,2.3,4.5])
a2

array([1.2, 2.3, 4.5])

In [11]:
print(a2.dtype)

float64


In [12]:
print(a2.itemsize)

8


In [13]:
# we can also set custom dtype while declaring the array -> here i am setting them to complex numbers
a3 = np.array([[1,2],[1,3],[1,1]], dtype=complex)
a3

array([[1.+0.j, 2.+0.j],
       [1.+0.j, 3.+0.j],
       [1.+0.j, 1.+0.j]])

In [14]:
# zeroes is a special function to create a dummy array of a given size initialized with zeroes
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [15]:
# similarly ones also exist
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [16]:
# And we can also fill them up with garbage values
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
# creating an array with a sequential range, we can also specify by how much we want the value to loop
np.arange(1,10,2) # works with float data type as well

array([1, 3, 5, 7, 9])

In [18]:
from numpy import pi
pi

3.141592653589793

In [19]:
np.linspace(0,9,5) # fills the array with a 5 numbers from the rang of 0 to 9

array([0.  , 2.25, 4.5 , 6.75, 9.  ])

In [20]:
x = np.linspace(0,100,25)
f = np.sin(x)


# Basic Operations

In [21]:
x = np.array([12,54,33,76,19])
y = np.arange(5)
y


array([0, 1, 2, 3, 4])

In [22]:
res = x -y # addition and subtraction can be done in same sized array
res

array([12, 53, 31, 73, 15])

In [23]:
# raises all the elements to the given exponent

res = res ** 2
res

array([ 144, 2809,  961, 5329,  225])

In [24]:
res = res*10 # scalar multiplication
res

array([ 1440, 28090,  9610, 53290,  2250])

In [25]:
# Matrix multiplication

A = np.array([[1,2],[3,4]])
B = np.array([[4,5],[6,7]])

# elementwise product
elem_prod = A * B

# matrix multiplication
mat_prod = A @ B

#dot prod (another way of doing matrix product)
dot = A.dot(B)

In [26]:
print(elem_prod,'\n')
print(mat_prod,'\n')
print(dot,'\n')

[[ 4 10]
 [18 28]] 

[[16 19]
 [36 43]] 

[[16 19]
 [36 43]] 



# Indexing, Slicing and Iterating

In [28]:
a = np.arange(10) ** 3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729], dtype=int32)