In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [2]:
import matplotlib.pyplot as plt

# This is gonna be a ground up implementation of the Sigmoid function for logistic regression
### In a linear funciton we have seen $f_w,_b(x^{(i)}) = w . x^{(i)} + b$ which gives us a number as prediciton, however in classification models we need our predictions to be in either true(1) or false(0) which can be achieved by using a sigmoid function that can map all the values given to it between 0 and 1.

## Formula for Sigmoid function:
### g(z) = $\frac{1}{1+e^{-z}}$

- in the case of a single example,  𝑧
  is scalar.
- in the case of multiple examples,  𝑧
  may be a vector consisting of  𝑚
  values, one for each example.

In [5]:
#Implemeting the sigmoid function
input_array = np.array([1,2,3])
exp_array = np.exp(input_array)
print(input_array)
print(exp_array)

[1 2 3]
[ 2.71828183  7.3890561  20.08553692]


In [11]:
def sigmoid(z):
#     z is an np array of size m
    g = 1/(1+np.exp(-z))
    return g

In [15]:
# generating sample sigmoid values for a sigmoid array
z_temp = np.arange(-10,11)
y_temp = sigmoid(z_temp)
m = z_temp.shape[0]
np.set_printoptions(precision=3)
print(np.c_[z_temp,y_temp])
    

[[-1.000e+01  4.540e-05]
 [-9.000e+00  1.234e-04]
 [-8.000e+00  3.354e-04]
 [-7.000e+00  9.111e-04]
 [-6.000e+00  2.473e-03]
 [-5.000e+00  6.693e-03]
 [-4.000e+00  1.799e-02]
 [-3.000e+00  4.743e-02]
 [-2.000e+00  1.192e-01]
 [-1.000e+00  2.689e-01]
 [ 0.000e+00  5.000e-01]
 [ 1.000e+00  7.311e-01]
 [ 2.000e+00  8.808e-01]
 [ 3.000e+00  9.526e-01]
 [ 4.000e+00  9.820e-01]
 [ 5.000e+00  9.933e-01]
 [ 6.000e+00  9.975e-01]
 [ 7.000e+00  9.991e-01]
 [ 8.000e+00  9.997e-01]
 [ 9.000e+00  9.999e-01]
 [ 1.000e+01  1.000e+00]]


In [ ]:
# The implementaion is really simple